version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  frontend:
    image: mathew-frontend
    build: ../frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
   image: mathew-backend
   build: ../backend
   env_file: .env
   volumes:
      - static:/backend_static/
      - media:/media/
   depends_on:
      - db
  
  gateway:
    image: infra-gateway
    build: ../infra
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
